baseURL = "https://vitess.io"
canonifyurls = true
disableKinds = ["taxonomy", "taxonomyTerm"]
enableGitInfo = true
googleAnalytics = "G-JWT03RNV4P"
enableRobotsTXT = true

# Syntax highlighting settings
pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsStyle = "fruity"

# Versions (folder-based)

[params.versions]
current = "20.0"
next = "21.0"

# end Versions

[params.assets]
js = ["app"]
fontawesomeversion = "6.1.2"

[params.social]
github        = "vitessio/vitess"
twitter       = "vitessio"
slack         = "https://vitess.io/slack"
stackoverflow = "vitess"

[params.blog]
subtitle = "Updates and insights from the **Vitess** team."

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5

# Language settings
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
disableLanguages = ["zh"]

# English
[languages.en]
title = "Vitess"
contentDir = "content/en"
languageName = "English"
weight = 1

[languages.en.params]
description = "Scalable. Reliable. MySQL-compatible. Cloud-native. Database."

# Chinese
[languages.zh]
title = "Vitess"
contentDir = "content/zh"
languageName = "中文 Chinese"
weight = 2

[languages.zh.params]
description = "Vitess是用于部署、扩展和管理大型MySQL实例集群的数据库解决方案。"
language_alternatives = ["en"]

# Features (English)
[[languages.en.params.features]]
title = "Scalability"
description = "Vitess is compatible with MySQL while extending its scalability. Its built-in sharding lets you grow your database without adding sharding logic to your application."
icon = "cubes"

[[languages.en.params.features]]
title = "Performance"
description = "Vitess improves on MySQL performance through query rewriting, caching and connection pooling. This allows the number of concurrent client connections to scale to orders of magnitude higher than traditional MySQL. Performance is monitored through nightly <a href='https://benchmark.vitess.io'>benchmarks</a>."
icon = "fighter-jet"

[[languages.en.params.features]]
title = "High Availability"
description = "Vitess automatically detects and repairs primary failures. Data migrations into Vitess, and resharding operations within Vitess are all accomplished with near-zero downtime."
icon = "tachometer-alt"

[[languages.en.params.features]]
title = "Features"
description = "Vitess improves on MySQL by providing materialized views and messaging features that work across shards."
icon = "share-alt"

[[languages.en.params.features]]
title = "Shard management"
description = "MySQL doesn't natively support sharding, but you will likely need it as your database grows. Vitess provides flexible sharding schemes that are completely transparent to the application. It also enables live resharding with minimal read-only downtime."
icon = "object-ungroup"

[[languages.en.params.features]]
title = "Schema Management"
description = "Vitess allows you to easily manage your schema while maintaining consistency across shards. Schema changes happen in the background without disrupting running workloads. This feature comes with a rich set of monitoring and fine-grained controls."
icon = "magic"

# Features (Chinese)
[[languages.zh.params.features]]
title = "扩展性"
description = "Vitess集Mysql数据库的很多重要特性和NoSQL数据库的可扩展性于一体。其内建拆分分片功能使您能够对您的MySQL数据库集群无限水平扩展，同时无需为应用添加分片逻辑。"
icon = "cubes"

[[languages.zh.params.features]]
title = "性能"
description = "Vitess自动重写对数据库性能有损害的查询。它还使用缓存机制来调解查询，并防止重复查询同时到达您的数据库。通過每夜的<a href='https://benchmark.vitess.io'>基準</a>來監控性能表現。"
icon = "fighter-jet"

[[languages.zh.params.features]]
title = "管理"
description = "Vitess可以支持自动处理主故障转移和备份等功能。它使用分布式元数据服务来跟踪和管理服务器，使您的应用程序无需关心数据库拓扑变化。"
icon = "tachometer-alt"

[[languages.zh.params.features]]
title = "连接池"
description = "Vitess避免了MySQL连接的高内存开销。 Vitess服务器轻松地一次处理数千个连接。"
icon = "share-alt"

[[languages.zh.params.features]]
title = "分片管理"
description = "MySQL本身并不提供拆分分片功能，但是您的业务数据量增大到一定程度是您是需要增加集群的。Vitess提供在线拆分功能，只需要很少的时间就完成新集群的切换，无需您在应用程序中添加任何拆分逻辑。"
icon = "object-ungroup"

[[languages.zh.params.features]]
title = "工作流"
description = "Vitess会跟踪有关集群配置的所有元数据，以便集群拓扑始终是最新的，对不同的客户端保持一致。"
icon = "magic"

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.extensions]
typographer = false

[mediaTypes]
"text/netlify" = { }

[outputFormats.REDIRECTS]
mediaType = "text/netlify"
baseName = "_redirects"
notAlternative = true

[outputs]
home = [ "HTML", "REDIRECTS", "RSS", "Lunr" ]

[outputFormats.Lunr]
baseName = "index"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.lunr]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
