baseURL = "https://vitess.io"
title   = "Vitess"
disableKinds = ["taxonomy", "taxonomyTerms"]

[params.home]
title = "Vitess is a database clustering system for horizontal scaling of MySQL"

[params.assets]
js = ["jquery-3.3.1", "jquery-ui-1.12.1", "jquery.tocify-1.9.0", "app"]

[params.social]
github        = "vitessio/vitess"
twitter       = "vitessio"
slack         = "vitess"
stackOverflow = "vitess"
