[build]
publish = "public"
command = "make production-build"

[build.environment]
HUGO_VERSION = "0.65.3"

[context.deploy-preview]
command = "make preview-build"

[context.branch-deploy]
command = "make preview-build"

# Redirect to Slack invite link.
[[redirects]]
  from = "/slack"
  to = "https://join.slack.com/t/vitess/shared_invite/enQtMzIxMDMyMzA0NzA1LTYxMjk2M2M2NjAwNGY0ODljY2E1MjBlZjRkMmZmNDVkZTBhNDUxNzNkOGM4YmEzNWEwOTE2NjJiY2QyZjZjYTE"
  status = 302
